### Delete data
DELETE http://localhost:8080/api/v1/post/89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTc0NzkwNDIyOCwiZXhwIjoxNzQ3OTA1MTI4fQ.Rou4CuQGESJO-jSOf681esTvtD5hX0lOfbu7a2MAOOE
Accept: application/json

### Update data
PUT http://localhost:8080/api/v1/post/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTc0NzkwNDIyOCwiZXhwIjoxNzQ3OTA1MTI4fQ.Rou4CuQGESJO-jSOf681esTvtD5hX0lOfbu7a2MAOOE
Content-Type: application/json
Accept: application/json

{
  "title": "Pir mikilir",
  "content": "santana"
}


### Ambil data tertentu
GET http://localhost:8080/api/v1/post/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTc0NzkwNDIyOCwiZXhwIjoxNzQ3OTA1MTI4fQ.Rou4CuQGESJO-jSOf681esTvtD5hX0lOfbu7a2MAOOE
Accept: application/json

### Ambil semua data
GET http://localhost:8080/api/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTc0NzkwNDIyOCwiZXhwIjoxNzQ3OTA1MTI4fQ.Rou4CuQGESJO-jSOf681esTvtD5hX0lOfbu7a2MAOOE
Accept: application/json


### Tambah data
POST http://localhost:8080/api/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbbnVsbF0sImlhdCI6MTc0Nzg5NjkxMiwiZXhwIjoxNzQ3OTgzMzEyfQ.nJzy-3qzVkmkYqbW7_z1BUiZkUcpVlKBjSP050qCuj8
Content-Type: application/json

{
  "title": "Jhahaha",
  "content": "komarudin ini sangat sangat bagus banget dong"
}

