### Delete data
DELETE http://localhost:8080/api/v1/post/89
Accept: application/json

### Update data
PUT http://localhost:8080/api/v1/post/3
Content-Type: application/json
Accept: application/json

{
  "title": "Mang Uday",
  "content": "Purbasana"
}


### Ambil data tertentu
GET http://localhost:8080/api/v1/post/14
Accept: application/json

### Ambil semua data
GET http://localhost:8080/api/v1/post
Accept: application/json


### Tambah data
POST http://localhost:8080/api/v1/post
Content-Type: application/json

{
  "title": "Jhahaha",
  "content": "komarudin ini sangat sangat bagus banget dong"
}

